# Generated by Django 5.2 on 2025-05-20 09:32

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/api/document/media/', location=pathlib.PurePosixPath('/var/www/scraapy/scraapy-api-development1/protected_media')), upload_to='documents/'),
        ),
    ]
