# Generated by Django 5.2 on 2025-06-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_orderscrap_scrapitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscrap',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
