# Generated by Django 5.2 on 2025-06-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_orderscrap_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
