# Generated by Django 5.2 on 2025-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_scrapitem_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscrap',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
