# Generated by Django 5.2 on 2025-05-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_phoneotp_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='phone',
            new_name='contact_number',
        ),
    ]
