# Generated by Django 5.2 on 2025-05-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_rename_phone_phoneotp_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='contact_number',
            new_name='phone',
        ),
    ]
