# Generated by Django 5.2 on 2025-05-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_rename_contact_number_phoneotp_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='expires_at',
        ),
    ]
