# Generated by Django 5.0.14 on 2025-05-18 08:28

import bms.utils
import django.db.models.deletion
import inventory.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '__first__'),
        ('pms', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rate', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('notpaid', 'Not paid'), ('paid', 'Paid'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_delivery', models.BooleanField(default=False)),
                ('delivery_address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_province', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery_country', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('delivery_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('addressName', models.CharField(blank=True, help_text='Address name', max_length=100, null=True)),
                ('zatca_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('base64_invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('mds_document', models.FileField(blank=True, null=True, upload_to=inventory.utils.mds_upload_path)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('on_site_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('on_site_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('on_site_pickup', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('staff_note', models.CharField(blank=True, max_length=2000, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='inventory.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='bms.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_owner', to=settings.AUTH_USER_MODEL)),
                ('parent_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditional_services', to='bms.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='bms.orderitem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_extra_fields', to='inventory.fieldtype')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.utils.get_item_image_path)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_image', to='bms.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(blank=True, null=True, upload_to=bms.utils.order_item_report_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_report', to='bms.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('item', models.ForeignKey(limit_choices_to={'category__sub_item_type': [('fleet', 'Fleet')]}, on_delete=django.db.models.deletion.CASCADE, related_name='order_sub_item', to='bms.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='reviewing', max_length=50)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='bms.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingSystemAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrackingSystemAddresses_destination', to='pms.address')),
                ('pickup_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TrackingSystemAddresses_pickup', to='pms.address')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_system_addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_addresses', to='bms.trackingsystemaddresses'),
        ),
    ]
