# Generated by Django 5.2 on 2025-05-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Shipping'), ('express', 'Express Shipping'), ('pickup', 'In-store Pickup')], max_length=50, null=True),
        ),
    ]
