# Generated by Django 5.2 on 2025-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_order_shipping_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
