# Generated by Django 5.0.14 on 2025-05-18 08:31

import django.db.models.deletion
import driver.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('id_number', models.CharField(max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('model_year', models.CharField(max_length=10)),
                ('plate_number', models.CharField(max_length=20)),
                ('driver_id_file', models.FileField(blank=True, null=True, upload_to=driver.models.documents_upload_path)),
                ('driver_id_expiry', models.DateField(blank=True, null=True)),
                ('license_file', models.FileField(blank=True, null=True, upload_to=driver.models.documents_upload_path)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('vehicle_registration_file', models.FileField(blank=True, null=True, upload_to=driver.models.documents_upload_path)),
                ('vehicle_registration_expiry', models.DateField(blank=True, null=True)),
                ('insurance_file', models.FileField(blank=True, null=True, upload_to=driver.models.documents_upload_path)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('employer', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'business'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started_journey', ' Started Journey'), ('picked_up', 'Picked up'), ('dropped_off', 'Dropped Off')], default='started_journey', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_tracking', to='bms.orderitem')),
                ('tracking_system_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_tracking', to='bms.trackingsystemaddresses')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='driver.driverprofile')),
            ],
        ),
    ]
