# Generated by Django 5.2 on 2025-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_alter_user_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'business'), ('driver', 'Driver'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=10),
        ),
    ]
