# Generated by Django 5.2 on 2025-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('driver', 'Driver'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=10),
        ),
    ]
