# Generated by Django 5.2 on 2025-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_user_pickup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='business_icons/'),
        ),
    ]
