# Generated by Django 5.0.14 on 2025-05-18 08:31

import django.db.models.deletion
import inventory.models
import inventory.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('product', 'Product'), ('rental', 'Rental'), ('service', 'Service')], max_length=10)),
                ('icon', models.FileField(blank=True, null=True, upload_to=inventory.utils.get_categorygroup_icon_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('file', 'File')], default='text', max_length=10)),
                ('icon', models.FileField(blank=True, null=True, upload_to=inventory.utils.get_field_type_icon_path)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('valid_options', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('requirements', models.JSONField(blank=True, null=True, validators=[inventory.models.validate_user_fields])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('price_unit', models.CharField(max_length=100, validators=[inventory.models.validate_price_unit])),
                ('price_unit_ar', models.CharField(blank=True, max_length=100, null=True, validators=[inventory.models.validate_price_unit])),
                ('sub_item_type', models.CharField(blank=True, choices=[('fleet', 'Fleet')], max_length=10, null=True)),
                ('hide_price', models.BooleanField(default=False)),
                ('require_contract', models.BooleanField(default=False)),
                ('contract_text', models.TextField(blank=True, null=True)),
                ('send_certificate', models.BooleanField(default=False)),
                ('associated_categories', models.ManyToManyField(blank=True, to='inventory.category')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('category_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.categorygroup')),
                ('field_types', models.ManyToManyField(blank=True, related_name='categories', to='inventory.fieldtype')),
                ('legal_requirements', models.ManyToManyField(blank=True, related_name='categories', to='inventory.legalrequirements')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=100)),
                ('on_site_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('on_site_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('on_site_pickup', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('minimum_selling_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('mds_document', models.FileField(blank=True, null=True, upload_to=inventory.utils.mds_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('staff_note', models.CharField(blank=True, max_length=2000, null=True)),
                ('last_max_quantity', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.utils.get_item_image_path)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to=inventory.utils.get_item_document_path)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='inventory.fieldtype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_extra_field', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('numberPlate', models.CharField(blank=True, max_length=1000, null=True)),
                ('item', models.ForeignKey(limit_choices_to={'category__sub_item_type': [('fleet', 'Fleet')]}, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFilesSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=inventory.utils.rental_documents_upload_path)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.certificatetype')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.subitem')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImagesSubItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.utils.rental_documents_upload_path)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.subitem')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('model_year', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_specs', to='inventory.category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='vehicle_specs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vehiclespecs'),
        ),
    ]
